name: exseos-h-py311
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - patch
  - pip
  - graphviz
  - pip:
    - pandas
    - hls4ml==0.8.0
    - matplotlib
    - scikit-learn
    - tensorflow==2.12.0
    - qkeras==0.9.0
    - conifer
    - colorlog
    - psutil
    - tables
    - pydot
    - pyyaml
    - dill