# ExSeOS-H Hardware ML Workflow Manager
# Copyright (C) 2024  Alexis Maya-Isabelle Shuping

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from exseos.types.Result import Okay, Fail
from exseos.types.Variable import VariableSet, UnboundVariable
from exseos.workflow.stage.Stage import Stage

import numpy as np
from hls4ml.model import ModelGraph
from sklearn.metrics import accuracy_score


class EvalModel(Stage):
	input_vars = (
		UnboundVariable("model", ModelGraph, "The model to evaluate."),
		UnboundVariable("X", np.ndarray, "Test data for evaluation"),
		UnboundVariable("y", np.ndarray, "Labels for X"),
	)
	output_vars = (
		UnboundVariable("accuracy", float, "HLS simulation model accuracy"),
		UnboundVariable(
			"predictions",
			np.ndarray,
			"Predictions generated by the HLS simulation model",
		),
	)

	async def run(self, inputs: VariableSet, _):
		stat = inputs.check_all()
		if stat.is_fail:
			return stat

		try:
			y_predictions = inputs.model.predict(np.ascontiguousarray(inputs.X))

			accuracy = accuracy_score(
				np.argmax(inputs.y, axis=1), np.argmax(y_predictions, axis=1)
			)

			return Okay(
				(
					self.output_vars[0].bind(accuracy),
					self.output_vars[1].bind(y_predictions),
				)
			)
		except Exception as e:
			return Fail([e])
